---
title: "Законы работы сознания по В.М. Аллахвердову"
output:
  html_document:
    toc: yes
    toc_float: yes
  
    
urlcolor: blue

---

## 1	Закон Юма 

cлучайные события должны всегда оправдываться в сознании человека неслучайными причинами.	

## 2	Закон Фрейда-Фестингера

механизм сознания, столкнувшись с противоречивой информацией,начинает свою работу с того, что пытается исказить эту информацию или вообще удалить её с поверхности сознания.	


## 3	Закон разрыва шаблона

неожиданная смена контекста вызывает эмоциональный шок и сбой в поведении до тех пор, пока в результате работы защитного пояса сознания не произойдёт переинтерпретация ситуации, не будет найден новый контекст, с точки зрения которого и будет далее рассматриваться эта ситуация.	


## 4	Закон Узнадзе	

нарушение ситуативной закономерности ведёт к разрушению привычных схем поведения, к затруднениям в принятии самых простых решений, вызывает сбой в поведении и хаотические попытки избавиться от навязанной ситуацией закономерности.	


## 5	Закон Хика

чем менее вероятен предъявленный стимул или требуемая реакция, тем больше времени над этой ситуацией работает сознание.	


## 6	Закон Джеймса

всё неизменное исчезает из сознания, т. е. перестает осознаваться, или же происходит изменение данного сознанию представления об этом неизменном. Иначе говоря, осознаваться может только такая информация, которая меняется либо объективно, либо субъективно.	


## 7	Закон Ланге

вначале осознаётся нечто, отождествлённое с точностью до самых слабых критериев соответствия, а затем образ уточняется путём последовательного ужесточения этих критериев.	


## 8	Закон классификации

любой конкретный стимул (объект) всегда появляется в поверхностном содержании сознания лишь в качестве члена некоего класса стимулов (объектов), при этом класс не может состоять только из одного члена.	


## 9	Закон Витгенштейна-Рош

члены класса неравноправны, среди них есть более и менее типичные.	


## 10	Обобщение лингвистического закона и закона классификации

в базовом содержании сознания любой знак — омоним, т. е. может быть отнесён к разным классам в поверхностном содержании сознания, но при отнесении к какому-либо классу он становится синонимом, так как всегда существуют другие знаки, отнесённые к этому же классу.	


## 11	Закон Бардина

зона неразличения дифференциального признака сама может являться дифференциальным признаком.	


## 12	Закон последействия фигуры

повторное предъявление стимула побуждает сознание повторять ранее сделанный выбор ответа. В обобщенном виде — закон последействия позитивного выбора: при предъявлении стимула защитный пояс сознания прежде всего пытается отождествить его с одним из тех классов стимулов, который до этого уже был позитивно выбран.	


## 13	Закон последействия фона

повторное предъявление стимула из зоны неразличения побуждает сознание повторно не осознавать не данный при предшествующем предъявлении ответ. В обобщенном виде — закон последействия негативного выбора: при повторении одной и той же ситуации негативный выбор имеет тенденцию к сохранению в виде негативного выбора, а при изменении ситуации негативный выбор имеет тенденцию влиять на следующий позитивный выбор.	
